version: '3.3'

services:
    api:
        build: ./
        depends_on:
            - database
        env_file:
            - .env
        ports:
            - "3000"
        restart: always
        volumes:
            - ./src:/home/app/joule
            - /home/app/joule/node_modules
            - ./log/api:/var/log/joule
            - ./log/api/npm:/home/app/.npm
    database:
        env_file:
            - .env
        image: mysql:latest
        ports:
            - "3306"
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    web:
        command: --conf /etc/Caddyfile
        depends_on:
            - api
        image: abiosoft/caddy:latest
        ports:
            - "8080:8080"
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - caddy-data:/etc/caddycerts
            - ./Caddyfile:/etc/Caddyfile
            - ./log/caddy:/var/log/caddy
            - ./src/public/dist:/var/www/joule

volumes:
    caddy-data:
    db-data:
