version: '3.3'

services:
	api:
		command: npm start
		depends_on:
			- database
		env_file:
			- .env
		image: node:latest
		restart: always
		volumes:
			- ../:/var/www/joule
	database:
		build:
			context: ./mysql
		env_file:
			- .env
		ports:
			- "3306"
		restart: always
		volumes:
			- db-data:/var/lib/mysql
	web:
		command: --conf /etc/Caddyfile
		depends_on:
			- api
		image: abiosoft/caddy:latest
		ports:
			- "80:80"
			- "443:443"
		restart: always
		volumes:
			- caddy-data:/etc/caddycerts
			- ./caddy/Caddyfile:/etc/Caddyfile
			- ../log/caddy:/var/log/caddy
			- ../src/site:/var/www/joule

volumes:
	caddy-data:
	db-data:
